### ISSUE TITLE
Hardcoding the PID file path prevents multiple users running Feather simultaneously - Possibly include username in filename? 

### ISSUE THREAD

**Issue by james-mcgoodwin** [danrue/feather#10]
Hi there, 

This is perhaps an edge case, but I thought it was worth mentioning. 

I use Feather on my Mac and have two different accounts I use, one for work, one for home life. 

As a result, I have to different Feather configs, each one backing up the home directory of the user it's applied to. 

Feather does not run as root, but is executed as each user. 

Further, each user has their own tarsnap cache, tarsnap keys, etc. Backups for user1 are thus separated from backups for user2. User1 cannot access backups for user2, and vice versa. I prefer that data isolation. 

Often (IE: always) I have both accounts logged in so I can switch between them.

I've used [Launch Control](http://www.soma-zone.com/LaunchControl/) to build out launchd(8) services for each user. On the chance that's not a familiar system, think of it as just how MacOS does cron. 

This is where things go askew. 

If Feather fires off for user1, it drops a PID file at /tmp/feather.pid, owned by user1. 

Then, if user2 kicks off it's copy of Feather, it fails because the pid file is already taken by user1. 

Two questions then follow: 

1. Is it critical or necessary to ensure only a single instance of Feather is operating on a computer at a time? (IE: Does/should it run independantly for multiple users?)

2. If the answer to (1) is that there's no resource collision if two user accounts run Feather at once, would it be reasonable to make the PID file path something that is user specific. Say something like PIDFILE = "/tmp/feather_${USERNAME}.pid"

Below is a snippit of log from the 'user2' account generated when this problem occurs. 

Thanks!

```
Traceback (most recent call last):
  File "/Users/user2/git/feather/feather", line 466, in <module>
    main()
  File "/Users/user2/git/feather/feather", line 458, in main
    lock(PIDFILE)
  File "/Users/user2/git/feather/feather", line 124, in __init__
    os.remove(pidfile)
OSError: [Errno 13] Permission denied: '/tmp/feather.pid'
```

And this is a stat of the PID file at the time: 
```
$  stat /tmp/feather.pid
16777220 147450308 -rw-r--r-- 1 user1 wheel 0 5 "Oct 17 10:59:36 2016" "Oct 17 10:59:36 2016" "Oct 17 10:59:36 2016" "Oct 17 10:59:36 2016" 4096 8 0 /tmp/feather.pid
```

**Comment by danrue** [comment]
It seems like making pidfile_path configurable in the config may be the best solution here?

**Comment by james-mcgoodwin** [comment]
That could do the trick quite nicely. 

Users who dont need the feature dont have weirdly named pidfiles. 

Users who do can set up a path to something in a home directory or somewhere. 

If that works for you then I think it would solve the edge case, which lets admit is rather esoteric!

**Comment by danrue** [comment]
Taking a look at the implementation, it may be easier to make it a command line argument. Otherwise it'll have to be refactored to move locking into the feather class.

**Comment by james-mcgoodwin** [comment]
I feel it's fine to take the simplest route for now. 

If this is something that ends up bugging you and you want to include it as part of the YAML structure later, then go for it. 

But throwing the pid path as a param to the feather invocation works fine for me.

**Comment by danrue** [comment]
Would you be so kind as to review and test #11?

**Comment by james-mcgoodwin** [comment]
HHmm...ok...so that's interesting. 

Check out the failure below.

```
$  ./feather -vvvvv /Users/yennix/git/feather/feather_lp-257_yennix.yaml
Traceback (most recent call last):
  File "./feather", line 473, in <module>
    main()
  File "./feather", line 465, in main
    lock(PIDFILE)
  File "./feather", line 129, in __init__
    file(pidfile,'w+').write("%s" % str(os.getpid()))
IOError: [Errno 2] No such file or directory: '/tmp/feather-LXg/t+08.pid'
```

It looks like the path to the config file string is not producing an expected base64 string. 

At least I certainly don't expect your change to produce characters outside the [a-z][A-Z][0-9] range. 

But looking at the above output, this was what happened: 
'/Users/yennix/git/feather/feather_lp-257_yennix.yaml' --> (sha1/base64 transformation) --> 'LXg/t+08'

If I copy the .yaml to another path (/tmp/feather_lp-257_yennix.yaml), and rerun feather, everything is great.

**Comment by james-mcgoodwin** [comment]
Yeah...that's super crazy. 
I'm getting successful execution when I copy/rename my yaml file to anything else. Even within the same directory. 
Something about //this precise order of letters// seems to be bugging the sha1/base64 transformation. 

Some more interesting output for you: 

```
[16:54:02] yennix @ LP-257.local  LastReturnCode: 0 ~/git/feather (remotes/origin/make_pidfile_unique % u=)
$ $ $  find ${HOME}/git/feather -iname '*.yaml' -ls
7494477        8 -rw-r--r--    1 yennix           staff                1463 Sep 30 19:50 /Users/yennix/git/feather/feather_lp-257_yennix.yaml
7584723        8 -rw-r--r--    1 yennix           staff                1463 Oct 18 16:53 /Users/yennix/git/feather/feather_lp-257_yennix_2.yaml

[16:54:27] yennix @ LP-257.local  LastReturnCode: 0 ~/git/feather (remotes/origin/make_pidfile_unique % u=)
$ $ $  ./feather -vvvvv /Users/yennix/git/feather/feather_lp-257_yennix.yaml
Traceback (most recent call last):
  File "./feather", line 473, in <module>
    main()
  File "./feather", line 465, in main
    lock(PIDFILE)
  File "./feather", line 129, in __init__
    file(pidfile,'w+').write("%s" % str(os.getpid()))
IOError: [Errno 2] No such file or directory: '/tmp/feather-LXg/t+08.pid'

[16:54:39] yennix @ LP-257.local  LastReturnCode: 1 ~/git/feather (remotes/origin/make_pidfile_unique % u=)
$ $ $  ./feather -vvvvv /Users/yennix/git/feather/feather_lp-257_yennix_2.yaml
Listing archives using tarsnap --list-archives
<<Feather successfully executes at this point>>
```

I can also prove that feather execution with 'feather_lp-257_yennix.yaml' does NOT produce a pid file of any name. I mean, of course it doesn't, but I just wanted to double check my /tmp to be utterly sure.

**Comment by danrue** [comment]
Ah. base64 includes + and /, which won't work on a filesystem (easily). I'll take it out. I was just trying to get a bit more entropy into the hash, but realistically, just using sha1 should be fine too.

**Comment by danrue** [comment]
I updated #11. Please re-test. I'm glad you just happened to stumble upon that bug :)

**Comment by james-mcgoodwin** [comment]
Yeah, me too. 

I utterly forgot base64 included +/= 

Will gitpull and retry now:)

**Comment by james-mcgoodwin** [comment]
Yup. That's running cleanly for me now, and making the pidfiles as expected. I'm able to run two different config files and get one pid file for each, as expected. 

Looks good dude:)

**Comment by danrue** [comment]
Merging. Thanks for testing!

**Comment by james-mcgoodwin** [comment]
Glad to help dude! Thanks for the wonderful tool. It's incredibly helpful!
