### ISSUE TITLE
Manage partial archives

### ISSUE THREAD

**Issue by mkaito** [danrue/feather#12]
Hi!

There are times when tarsnap doesn't finish running, perhaps because the network goes down, or because I turn the computer off while it's running. Since it runs every hour and I don't actively monitor it, it happens.

This often results in partial archives. I think feather should either try to reuse these or delete them on the next run.

**Comment by danrue** [comment]
Are you specifying --checkpoint-bytes ? If you do, it should pick up from the last checkpoint. As far as partials, it looks like it is hard coded to delete them after 7 days. I'm looking at https://github.com/danrue/feather/blob/master/feather#L331-L341

**Comment by mkaito** [comment]
I didn't realize it deletes them after 7 days. That makes sense.

I'm not sure about `--checkpoint-bytes`. Do I need to specify that in the feather config?

**Comment by danrue** [comment]
Yup, specify it like so: 

```yaml
# perform a checkpoint every 100MB
backup_args: "--checkpoint-bytes 104857600"
```

**Comment by mkaito** [comment]
Ah yes. That seems to be a default option. That is indeed in my config.

Thanks a lot!
