### ISSUE TITLE
Is feather unmaintained?

### ISSUE THREAD

**Issue by mkaito** [danrue/feather#14]
I see the last commit was in October 2016. Are you no longer using/maintaining feather?

**Comment by danrue** [comment]
Hi mkaito - I no longer use tarsnap. I have looked at modernizing feather (python3, pip support, tests, etc), but it hasn't been a priority, and probably won't bubble up unless I start using tarsnap again. As far as I know, people do still use it, and I'm happy to merge improvements. Does that answer your question?

**Comment by mkaito** [comment]
Yes, thank you!

And thanks for all the work on feather.

El 21 de febrero de 2018 3:09:38 GMT+00:00, Dan Rue <notifications@github.com> escribió:
>Hi mkaito - I no longer use tarsnap. I have looked at modernizing
>feather (python3, pip support, tests, etc), but it hasn't been a
>priority, and probably won't bubble up unless I start using tarsnap
>again. As far as I know, people do still use it, and I'm happy to merge
>improvements. Does that answer your question?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/danrue/feather/issues/14#issuecomment-367199867

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.
